export interface NotificationType {
  EVENT_UPDATED: "EVENT_UPDATED";
  EVENT_CANCELLED: "EVENT_CANCELLED";
  EVENT_REMINDER: "EVENT_REMINDER";
  ATTENDANCE_APPROVED: "ATTENDANCE_APPROVED";
  ATTENDANCE_REJECTED: "ATTENDANCE_REJECTED";
  ATTENDANCE_REQUEST_RECEIVED: "ATTENDANCE_REQUEST_RECEIVED";
  GENERAL_ANNOUNCEMENT: "GENERAL_ANNOUNCEMENT";
}
